backend:
  name: git-gateway
  branch: master

media_folder: "imagenes"
public_folder: "/imagenes"

collections:
  - name: "reseñas"
    label: "Reseñas de Libros"
    folder: "reseñas"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Autor", name: "author", widget: "string" }
      - { label: "Año", name: "year", widget: "string" }
      - { label: "Género", name: "genre", widget: "string" }
      - { label: "Imagen destacada", name: "image", widget: "image" }
      - { label: "Reseña", name: "body", widget: "markdown" }
